name: Android Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant Permission
      run: chmod +x gradlew || echo "gradlew not found, will generate"

    - name: Setup Gradle
      run: |
        gradle wrapper --gradle-version 8.5
        chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew assembleDebug --info
