name: Android Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Purani files ko hata dein taaki conflict na ho
    - name: Clean up old wrapper
      run: rm -f gradlew

    # Gradle wrapper ko naye siras se generate karein
    - name: Setup Gradle
      run: gradle wrapper --gradle-version 8.4

    # File ko executable banayein
    - name: Grant execute permission
      run: chmod +x gradlew

    # Build run karein
    - name: Build with Gradle
      run: ./gradlew assembleDebug --info
